"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Papa from "papaparse";
import * as XLSX from "xlsx";
import { Briefcase, CheckCircle2, ChevronDown, CircleAlert, CloudUpload, Loader2, Search, X } from "lucide-react";
import { halalMock } from "@/lib/halal-mock";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type SearchResult = { ticker: string; name: string; exchange: string; type: string; isin?: string };
type Account = "PEA" | "CTO" | "Compte crypto" | "Autre";
type Broker = "Trade Republic" | "Degiro" | "Fortuneo" | "Bitpanda";
type HalalStatus = "compliant" | "non_compliant" | "debated" | "unknown";
type ImportAsset = { name: string; ticker: string | null; isin: string | null; type: "stock" | "etf" | "crypto" | "gold" | "cash"; quantity: number; averagePrice: number; currency: string; account: Account; purchaseDate: string; status: HalalStatus };
type Errors = Partial<Record<"quantity" | "averagePrice" | "purchaseDate" | "account" | "submit", string>>;
const brokers: Broker[] = ["Trade Republic", "Degiro", "Fortuneo", "Bitpanda"];
const help: Record<Broker, string> = { Fortuneo: "Bourse → Mon portefeuille → Exporter → XLS", Bitpanda: "Paramètres → Historique → Exporter CSV", "Trade Republic": "Profil → Documents → Exporter", Degiro: "Activité → Exporter" };
const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", minimumFractionDigits: 2 });

function assetType(value: string): ImportAsset["type"] { const type = value.toUpperCase(); if (type.includes("ETF")) return "etf"; if (type.includes("CRYPTO")) return "crypto"; if (type.includes("GOLD") || type.includes("METAL") || type === "XAU") return "gold"; if (type.includes("CASH")) return "cash"; return "stock"; }
function statusFor(ticker?: string | null, name?: string): HalalStatus { const result = (ticker && (halalMock[ticker] ?? halalMock[ticker.split(".")[0]])) || undefined; if (result) return result.status; if (/ISLAMIC/i.test(name ?? "")) return "compliant"; return "unknown"; }
function statusLabel(status: HalalStatus) { return status === "compliant" ? "Conforme" : status === "non_compliant" ? "Non conforme" : status === "debated" ? "Douteux" : "Non analysé"; }
function numeric(value: unknown) { return Number(String(value ?? "").replace(/\s/g, "").replace(/€/g, "").replace(",", ".")); }
function isoDate(value: unknown) { const raw = String(value ?? "").trim(); if (!raw) return new Date().toISOString().slice(0, 10); const match = raw.match(/^(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{4})/); if (match) return `${match[3]}-${match[2].padStart(2, "0")}-${match[1].padStart(2, "0")}`; const parsed = new Date(raw); return Number.isNaN(parsed.getTime()) ? new Date().toISOString().slice(0, 10) : parsed.toISOString().slice(0, 10); }
function get(row: Record<string, unknown>, ...keys: string[]) { const actual = Object.keys(row).find((key) => keys.some((wanted) => key.trim().toLowerCase() === wanted.toLowerCase())); return actual ? row[actual] : ""; }

export function AddAssetModal({ open, onClose, initialAsset = null }: { open: boolean; onClose: () => void; initialAsset?: SearchResult | null }) {
  const router = useRouter();
  const fileRef = useRef<HTMLInputElement>(null);
  const [tab, setTab] = useState("manual");
  const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResult[]>([]); const [searching, setSearching] = useState(false); const [searchOpen, setSearchOpen] = useState(false);
  const [selected, setSelected] = useState<SearchResult | null>(null); const [currentPrice, setCurrentPrice] = useState<number | null>(null); const [priceLoading, setPriceLoading] = useState(false);
  const [quantity, setQuantity] = useState(""); const [averagePrice, setAveragePrice] = useState(""); const [purchaseDate, setPurchaseDate] = useState(""); const [account, setAccount] = useState<Account | "">(""); const [errors, setErrors] = useState<Errors>({}); const [submitting, setSubmitting] = useState(false);
  const [broker, setBroker] = useState<Broker>("Fortuneo"); const [file, setFile] = useState<File | null>(null); const [importRows, setImportRows] = useState<ImportAsset[]>([]); const [importError, setImportError] = useState(""); const [dragging, setDragging] = useState(false); const [helpOpen, setHelpOpen] = useState(false); const [progress, setProgress] = useState(0);
  const [toast, setToast] = useState("");

  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 4000); return () => window.clearTimeout(timer); }, [toast]);
  useEffect(() => { if (open && initialAsset) { void chooseAsset(initialAsset); setTab("manual"); } if (!open) { clearAsset(); setQuantity(""); setAveragePrice(""); setPurchaseDate(""); setAccount(""); setErrors({}); } }, [open, initialAsset?.ticker]);
  useEffect(() => { const value = query.trim(); if (!value || selected) { setResults([]); setSearchOpen(false); return; } const controller = new AbortController(); const timer = window.setTimeout(async () => { setSearching(true); try { const response = await fetch(`/api/search-assets?q=${encodeURIComponent(value)}`, { signal: controller.signal }); if (!response.ok) throw new Error("Recherche indisponible"); setResults(await response.json()); setSearchOpen(true); } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) { setResults([]); setSearchOpen(true); } } finally { if (!controller.signal.aborted) setSearching(false); } }, 300); return () => { clearTimeout(timer); controller.abort(); }; }, [query, selected]);

  async function chooseAsset(asset: SearchResult) { setSelected(asset); setQuery(""); setSearchOpen(false); setCurrentPrice(null); setPriceLoading(true); try { const response = await fetch("/api/prices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assets: [{ isin: asset.ticker, ticker: asset.ticker, name: asset.name, currency: "EUR" }] }) }); if (!response.ok) throw new Error("Prix Yahoo Finance indisponible"); const prices = await response.json() as Record<string, number | null>; setCurrentPrice(prices[asset.ticker] ?? null); } catch { setCurrentPrice(null); } finally { setPriceLoading(false); } }
  function clearAsset() { setSelected(null); setQuery(""); setCurrentPrice(null); setErrors({}); }
  function validate() { const next: Errors = {}; const qty = numeric(quantity); const price = numeric(averagePrice); if (!quantity || !Number.isFinite(qty) || qty <= 0) next.quantity = "La quantité doit être supérieure à 0."; if (!averagePrice || !Number.isFinite(price) || price <= 0) next.averagePrice = "Le prix d’achat doit être supérieur à 0."; if (!purchaseDate) next.purchaseDate = "La date d’achat est requise."; else if (purchaseDate > new Date().toISOString().slice(0, 10)) next.purchaseDate = "La date ne peut pas être dans le futur."; if (!account) next.account = "Sélectionnez un compte."; setErrors(next); return Object.keys(next).length === 0; }
  async function submitManual() { if (!selected || !validate()) return; setSubmitting(true); setErrors({}); try { const supabase = createClient(); const { data: { user }, error: authError } = await supabase.auth.getUser(); if (authError || !user) throw new Error("Session expirée. Veuillez vous reconnecter."); const status = statusFor(selected.ticker, selected.name); const { error } = await supabase.from("assets").insert({ user_id: user.id, name: selected.name, ticker: selected.ticker, isin: selected.isin ?? null, type: assetType(selected.type), quantity: numeric(quantity), average_buy_price: numeric(averagePrice), current_price: currentPrice, currency: "EUR", broker: "manuel", account_type: account || null, purchase_date: purchaseDate, halal_status: status }); if (error) throw error; onClose(); setToast("Actif ajouté avec succès"); router.refresh(); clearAsset(); setQuantity(""); setAveragePrice(""); setPurchaseDate(""); setAccount(""); } catch (error) { setErrors({ submit: error instanceof Error ? error.message : "Impossible d’ajouter l’actif." }); } finally { setSubmitting(false); } }

  async function parseFile(nextFile: File) { setFile(nextFile); setImportRows([]); setImportError(""); try { let source: Record<string, unknown>[]; if (/\.csv$/i.test(nextFile.name)) { const text = (await nextFile.text()).replace(/^\uFEFF/, ""); const lines = text.split(/\r?\n/); const skip = broker === "Bitpanda" ? 5 : broker === "Fortuneo" ? 3 : 0; const parsed = Papa.parse<Record<string, unknown>>(lines.slice(skip).join("\n"), { header: true, skipEmptyLines: true, transformHeader: (header) => header.trim() }); if (parsed.errors.length && !parsed.data.length) throw new Error(parsed.errors[0].message); source = parsed.data; } else { const workbook = XLSX.read(await nextFile.arrayBuffer(), { cellDates: true }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; if (!sheet) throw new Error("Le fichier ne contient aucune feuille."); const matrix = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: "" }); const expected = broker === "Fortuneo" ? ["Libellé", "ISIN"] : broker === "Degiro" ? ["Produit", "ISIN"] : ["Asset"]; const headerIndex = matrix.findIndex((row) => expected.every((header) => row.some((cell) => String(cell).trim() === header))); if (headerIndex < 0) throw new Error(`Format ${broker} non reconnu.`); const headers = matrix[headerIndex].map(String); source = matrix.slice(headerIndex + 1).map((row) => Object.fromEntries(headers.map((header, index) => [header, row[index]]))); }
      const mapped = source.flatMap((row): ImportAsset[] => { if (broker === "Bitpanda" && String(get(row, "Transaction Type", "Type")).toLowerCase() !== "buy") return []; const name = String(get(row, "Libellé", "Produit", "Asset", "Nom")).trim(); const isin = String(get(row, "ISIN")).trim() || null; const qty = numeric(get(row, "Qté", "Quantité", "Shares", "Amount Asset")); const price = numeric(get(row, "PRU", "Cours", "Price", "Asset market price")); if (!name || !Number.isFinite(qty) || qty <= 0 || !Number.isFinite(price) || price <= 0) return []; const rawType = String(get(row, "Asset class", "Type")); const ticker = String(get(row, "Ticker", "Asset")).trim() || isin; const type = broker === "Bitpanda" ? assetType(rawType || ticker || "crypto") : assetType(rawType || name); const purchase = isoDate(get(row, "Date", "Timestamp")); const exportedAccount = String(get(row, "account_type", "Compte")).trim(); const acct: Account = broker === "Bitpanda" ? "Compte crypto" : exportedAccount === "PEA" ? "PEA" : exportedAccount === "Autre" ? "Autre" : "CTO"; return [{ name, ticker, isin, type, quantity: qty, averagePrice: price, currency: String(get(row, "Dev", "Currency", "Fiat")).trim() || "EUR", account: acct, purchaseDate: purchase, status: statusFor(ticker, name) }]; }); if (!mapped.length) throw new Error(`Aucun actif valide détecté dans cet export ${broker}.`); setImportRows(mapped); } catch (error) { setFile(null); setImportError(error instanceof Error ? error.message : "Impossible de lire le fichier."); } }
  function clearFile() { setFile(null); setImportRows([]); setImportError(""); setProgress(0); if (fileRef.current) fileRef.current.value = ""; }
  async function confirmImport() { if (!importRows.length) return; setSubmitting(true); setImportError(""); setProgress(0); try { const supabase = createClient(); const { data: { user }, error: authError } = await supabase.auth.getUser(); if (authError || !user) throw new Error("Session expirée. Veuillez vous reconnecter."); let imported = 0; for (let index = 0; index < importRows.length; index++) { const row = importRows[index]; const { error } = await supabase.from("assets").upsert({ user_id: user.id, name: row.name, ticker: row.ticker, isin: row.isin, type: row.type, quantity: row.quantity, average_buy_price: row.averagePrice, current_price: row.averagePrice, currency: row.currency, broker: broker.toLowerCase().replace(" ", "_"), account_type: row.account, purchase_date: row.purchaseDate, halal_status: row.status }, { onConflict: "user_id,ticker,purchase_date", ignoreDuplicates: true }); if (error) throw error; imported++; setProgress(index + 1); } onClose(); setToast(`${imported} actifs importés avec succès`); clearFile(); router.refresh(); } catch (error) { setImportError(error instanceof Error ? error.message : "L’import a échoué."); } finally { setSubmitting(false); } }

  const qty = numeric(quantity) || 0; const avg = numeric(averagePrice) || 0; const value = currentPrice === null ? null : qty * currentPrice; const gain = currentPrice === null ? null : (currentPrice - avg) * qty; const manualStatus = selected ? statusFor(selected.ticker, selected.name) : "unknown";
  return <>
    <Dialog open={open} onOpenChange={(next) => { if (!next && !submitting) onClose(); }}><DialogContent className="border-white/[0.05] bg-[#111412] p-0 text-[#ffffff] sm:max-w-[650px]"><DialogHeader className="px-5 pt-5 sm:px-8 sm:pt-7"><DialogTitle>Ajouter un actif</DialogTitle></DialogHeader>
      <Tabs value={tab} onValueChange={setTab} className="px-5 pb-5 sm:px-8 sm:pb-8"><TabsList className="mt-4 grid w-full grid-cols-2 border-b border-white/[0.05]"><TabsTrigger value="manual" className="border-b-2 border-transparent py-4 font-semibold text-[rgba(255,255,255,0.6)] data-[state=active]:border-[#c9a84c] data-[state=active]:text-[#e6c364]">Saisie manuelle</TabsTrigger><TabsTrigger value="csv" className="border-b-2 border-transparent py-4 font-semibold text-[rgba(255,255,255,0.6)] data-[state=active]:border-[#c9a84c] data-[state=active]:text-[#e6c364]">Import CSV</TabsTrigger></TabsList>
        <TabsContent value="manual" className="mt-5 space-y-5"><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-[#8f8878]" /><Input value={query} onChange={(event) => { if (selected) clearAsset(); setQuery(event.target.value); }} onFocus={() => query.trim() && setSearchOpen(true)} placeholder="Rechercher un actif (nom, ticker, ISIN...)" className="h-11 border-[#4d4637] bg-[#1a1c1a] pl-10" />{searchOpen && !selected && <div className="absolute z-20 mt-2 w-full overflow-hidden rounded-md border border-[#4d4637] bg-[#1b201c] shadow-xl">{searching ? <p className="p-4 text-sm"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Recherche...</p> : results.length ? results.map((result) => <button key={`${result.ticker}-${result.exchange}`} type="button" onClick={() => void chooseAsset(result)} className="flex w-full items-center gap-3 border-b border-white/[0.05] px-4 py-3 text-left last:border-0 hover:bg-[#282d29]"><span className="flex-1"><strong>{result.ticker}</strong> <span className="text-[rgba(255,255,255,0.6)]">{result.name}</span></span><span className="text-xs text-[#8f8878]">{result.exchange}</span><span className="rounded border border-[#4d4637] px-2 py-0.5 text-xs">{result.type}</span></button>) : <p className="p-4 text-sm text-[#8f8878]">Aucun actif trouvé.</p>}</div>}</div>
          {selected && <><div className="flex items-center gap-3 rounded-md border border-[#c9a84c] bg-[#1a1c1a] p-3"><Briefcase className="h-5 w-5 text-[#c9a84c]" /><div className="min-w-0 flex-1"><p className="truncate font-semibold">{selected.ticker} — {selected.name}</p><p className="text-xs text-[#8f8878]">{selected.exchange} • {selected.type}</p></div><button type="button" onClick={clearAsset} aria-label="Désélectionner"><X className="h-5 w-5" /></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Quantité" error={errors.quantity}><Input type="number" min="0.00000001" step="any" value={quantity} onChange={(event) => setQuantity(event.target.value)} className={fieldClass(errors.quantity)} /></Field><Field label="Prix d'achat moyen (€)" error={errors.averagePrice}><Input type="number" min="0.01" step="any" value={averagePrice} onChange={(event) => setAveragePrice(event.target.value)} className={fieldClass(errors.averagePrice)} /></Field><Field label="Date d'achat" error={errors.purchaseDate}><Input type="date" max={new Date().toISOString().slice(0, 10)} value={purchaseDate} onChange={(event) => setPurchaseDate(event.target.value)} className={`${fieldClass(errors.purchaseDate)} [color-scheme:dark]`} /></Field><Field label="Compte" error={errors.account}><Select value={account} onValueChange={(value) => setAccount(value as Account)}><SelectTrigger className={fieldClass(errors.account)}><SelectValue placeholder="Choisir un compte" /></SelectTrigger><SelectContent>{(["PEA", "CTO", "Compte crypto", "Autre"] as Account[]).map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field></div>
            <div className="rounded-lg border border-white/[0.05] border-l-4 border-l-[#c9a84c] bg-[#1a1c1a] p-4 text-sm"><Preview label="Valeur estimée" value={priceLoading ? "Chargement..." : value === null ? "Prix indisponible" : euro.format(value)} /><Preview label="Statut halal" value={statusLabel(manualStatus)} status={manualStatus} /><Preview label="+/- depuis achat" value={gain === null || !avg ? "—" : `${gain >= 0 ? "+" : ""}${euro.format(gain)}`} positive={gain !== null ? gain >= 0 : undefined} /></div></>}
          {errors.submit && <ErrorMessage>{errors.submit}</ErrorMessage>}<DialogFooter className="border-t border-white/[0.05] pt-4"><Button variant="ghost" onClick={onClose} disabled={submitting}>Annuler</Button><Button onClick={() => void submitManual()} disabled={!selected || submitting}>{submitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Ajouter à mon portefeuille</Button></DialogFooter>
        </TabsContent>
        <TabsContent value="csv" className="mt-5 space-y-5"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{brokers.map((item) => <button key={item} type="button" onClick={() => { setBroker(item); clearFile(); }} className={`border-b-2 px-2 py-3 text-xs font-semibold ${broker === item ? "border-[#c9a84c] text-[#e6c364]" : "border-transparent text-[rgba(255,255,255,0.6)]"}`}>{item}</button>)}</div>
          <button type="button" onClick={() => fileRef.current?.click()} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); const next = event.dataTransfer.files[0]; if (next) void parseFile(next); }} className={`flex min-h-48 w-full flex-col items-center justify-center rounded-xl border-2 border-dashed p-6 ${dragging ? "border-[#e6c364] bg-[#c9a84c]/10" : "border-[#8c762e] bg-[#111412]"}`}><CloudUpload className="mb-4 h-8 w-8 text-[#e6c364]" /><strong>Glissez votre fichier ici</strong><span className="text-sm text-[rgba(255,255,255,0.6)]">ou cliquez pour parcourir</span><span className="mt-3 text-xs text-[#8f8878]">.csv • .xls • .xlsx</span></button><input ref={fileRef} type="file" accept=".csv,.xls,.xlsx" className="hidden" onChange={(event) => { const next = event.target.files?.[0]; if (next) void parseFile(next); }} />
          {file && <div className="flex items-center gap-3 rounded-md border border-white/[0.05] bg-[#1a1c1a] p-3"><CheckCircle2 className="h-5 w-5 text-halal-compliant" /><span className="min-w-0 flex-1 truncate text-sm font-semibold">{file.name}</span><button type="button" onClick={clearFile}><X className="h-5 w-5" /></button></div>}{importError && <ErrorMessage>{importError}</ErrorMessage>}
          {!!importRows.length && <div className="overflow-x-auto rounded-lg border border-white/[0.05]"><table className="w-full min-w-[560px] text-xs"><thead className="bg-[#282d29] text-left"><tr>{["Actif", "ISIN", "Quantité", "PRU", "Statut halal"].map((title) => <th key={title} className="p-3">{title}</th>)}</tr></thead><tbody>{importRows.slice(0, 5).map((row, index) => <tr key={`${row.ticker}-${index}`} className="border-t border-white/[0.05]"><td className="p-3">{row.name}</td><td className="p-3">{row.isin ?? "—"}</td><td className="p-3">{row.quantity}</td><td className="p-3">{euro.format(row.averagePrice)}</td><td className="p-3">{statusLabel(row.status)}</td></tr>)}</tbody></table><p className="bg-[#282d29] p-3 text-xs">{importRows.length} actifs détectés • {importRows.filter((row) => row.status === "compliant").length} conformes • {importRows.filter((row) => row.status === "unknown").length} non analysés</p></div>}
          <div className="border-y border-white/[0.05]"><button type="button" onClick={() => setHelpOpen(!helpOpen)} className="flex w-full items-center justify-between py-4 text-left text-sm font-semibold">Comment exporter depuis {broker} ? <ChevronDown className={`h-4 w-4 transition-transform ${helpOpen ? "rotate-180" : ""}`} /></button>{helpOpen && <p className="pb-4 text-sm text-[rgba(255,255,255,0.6)]">{help[broker]}</p>}</div>{submitting && <p className="text-center text-sm text-[#e6c364]"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" />Import en cours... {progress}/{importRows.length} actifs</p>}
          <DialogFooter><Button variant="ghost" onClick={onClose} disabled={submitting}>Annuler</Button><Button onClick={() => void confirmImport()} disabled={!importRows.length || submitting}>{submitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Importer {importRows.length || ""} actif{importRows.length > 1 ? "s" : ""}</Button></DialogFooter>
        </TabsContent>
      </Tabs></DialogContent></Dialog>
    {toast && <div role="status" className="fixed bottom-5 right-5 z-[200] flex items-center gap-2 rounded-lg border border-emerald-500/40 bg-[#111412] px-4 py-3 text-sm text-white shadow-xl"><CheckCircle2 className="h-5 w-5 text-halal-compliant" />{toast}</div>}
  </>;
}

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="space-y-2"><span className="text-xs font-medium text-[rgba(255,255,255,0.6)]">{label}</span>{children}{error && <span className="flex items-center gap-1 text-xs text-halal-nonCompliant"><CircleAlert className="h-3 w-3" />{error}</span>}</label>; }
function fieldClass(error?: string) { return `h-11 bg-[#1a1c1a] ${error ? "border-red-500 focus-visible:ring-red-500" : "border-[#4d4637]"}`; }
function Preview({ label, value, status, positive }: { label: string; value: string; status?: HalalStatus; positive?: boolean }) { const color = status === "compliant" || positive === true ? "text-halal-compliant" : status === "non_compliant" || positive === false ? "text-halal-nonCompliant" : status === "debated" ? "text-halal-debated" : "text-[#ffffff]"; return <div className="flex items-center justify-between py-2"><span className="text-[rgba(255,255,255,0.6)]">{label}</span><strong className={color}>{value}</strong></div>; }
function ErrorMessage({ children }: { children: React.ReactNode }) { return <p className="flex items-center gap-2 rounded-md border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-300"><CircleAlert className="h-4 w-4 shrink-0" />{children}</p>; }
