"use client";

import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, ArrowRight, Check, CircleCheck, ChevronDown, Loader2, Search, ShieldCheck } from "lucide-react";
import type { CriterionResult, ScreeningResult } from "@/lib/aaoifi/types";

const initial: ScreeningResult = {
  status: "INSUFFICIENT_DATA", methodology: "AAOIFI_SCREENING_V1", companyName: "Apple Inc.", ticker: "AAPL", sector: "—", fiscalPeriod: "—",
  business: { key: "business", label: "Activité", status: "UNKNOWN", confidence: "LOW", explanation: "Lancez une analyse pour récupérer les données SEC/XBRL." }, criteria: [], limitations: [],
};

export function ScreeningView({ initialSymbol }: { initialSymbol?: string }) {
  const [query, setQuery] = useState(initialSymbol?.trim().toUpperCase() || "AAPL");
  const [result, setResult] = useState<ScreeningResult>(initial);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => {
    if (initialSymbol?.trim()) void analyze();
    // Runs once: the symbol comes from the URL the page was opened with.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  async function analyze(event?: FormEvent) {
    event?.preventDefault(); const ticker = query.trim().toUpperCase(); if (!ticker) return;
    setLoading(true); setError("");
    try { const response = await fetch("/api/alpha-screening", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticker }) }); const data = await response.json() as ScreeningResult & { error?: string }; if (!response.ok || data.error) throw new Error(data.error ?? "Analyse impossible."); setResult(data); }
    catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Analyse impossible."); }
    finally { setLoading(false); }
  }
  const statusText = result.status === "COMPLIANT" ? "COMPLIANT" : result.status === "NON_COMPLIANT" ? "NON_COMPLIANT" : result.status;
  return <main className="mx-auto max-w-[1180px] p-4 text-white sm:p-8">
    <section className="text-center"><span className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-primary"><ShieldCheck className="h-3.5 w-3.5" />Audit gratuit · SEC/XBRL</span><h1 className="mt-5 text-3xl font-bold">Screener d’actions halal</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Analyse déterministe selon AAOIFI_SCREENING_V1, avec provenance et limites explicites.</p><form onSubmit={analyze} className="mx-auto mt-7 flex max-w-2xl gap-2 rounded-xl border border-primary/40 bg-card p-2"><Search className="ml-2 mt-2.5 h-4 w-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" placeholder="Ticker : AAPL, AI.PA, SAP.DE, 7203.T, 2222.SR…" /><button disabled={loading} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-5 text-xs font-bold text-primary-foreground disabled:opacity-60">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Analyser"}<ArrowRight className="h-3.5 w-3.5" /></button></form>{error && <p className="mx-auto mt-3 max-w-2xl text-xs text-halal-nonCompliant">{error}</p>}</section>
    <section className="mx-auto mt-10 max-w-3xl overflow-hidden rounded-2xl border border-border bg-card"><div className="flex items-center justify-between gap-4 p-5"><div><h2 className="text-lg font-bold">{result.companyName}</h2><p className="text-xs text-muted-foreground">{result.ticker} · {result.sector ?? "Secteur non déterminé"}</p></div><span className="text-right text-[10px] uppercase text-muted-foreground">{result.methodology}<br /><strong className="text-white">{result.fiscalPeriod}</strong></span></div><div className={`flex items-center justify-center gap-2 py-4 text-sm font-bold uppercase tracking-wide ${result.status === "COMPLIANT" ? "bg-halal-compliant text-[#07150f]" : result.status === "NON_COMPLIANT" ? "bg-halal-nonCompliant text-white" : "bg-halal-debated text-[#1b1203]"}`}><CircleCheck className="h-5 w-5" />{statusText}</div><div className="p-5">{(result.reason || result.note) && <div className="mb-4 rounded-xl border border-white/10 bg-white/[0.03] p-4 text-xs leading-5">{result.reason && <p className="text-white">{result.reason}</p>}{result.note && <p className="mt-1 text-muted-foreground">{result.note}</p>}{result.confidence && <p className="mt-1 text-[10px] uppercase text-muted-foreground">Confiance : {result.confidence}</p>}</div>}<div className="grid gap-3 sm:grid-cols-2">{[result.business, ...result.criteria].map((criterion) => <Criterion key={criterion.key} criterion={criterion} />)}</div>{result.limitations.length > 0 && <div className="mt-5 rounded-xl border border-halal-debated/30 bg-halal-debated/[0.06] p-4"><p className="text-xs font-bold text-halal-debated">Limites et données non déterminées</p><ul className="mt-2 space-y-1 text-xs leading-5 text-muted-foreground">{result.limitations.map((item) => <li key={item}>• {item}</li>)}</ul></div>}<p className="mt-5 text-[10px] leading-4 text-muted-foreground">Les résultats sont basés sur les critères AAOIFI et les données financières publiques disponibles. Certains cas limites nécessitent une vérification manuelle. Ce n&apos;est pas une fatwa.</p></div></section>
  </main>;
}

function Criterion({ criterion }: { criterion: CriterionResult }) { const passed = criterion.status === "PASS"; const failed = criterion.status === "FAIL"; return <details className={`group rounded-xl border p-4 ${passed ? "border-halal-compliant/40 bg-halal-compliant/[0.05]" : failed ? "border-halal-nonCompliant/40 bg-halal-nonCompliant/[0.05]" : "border-halal-debated/40 bg-halal-debated/[0.05]"}`}><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span><span className="block text-[10px] text-muted-foreground">{criterion.label}</span><strong className="mt-2 block text-sm">{criterion.status}</strong></span><span className="flex items-center gap-2">{passed ? <Check className="h-3.5 w-3.5 text-halal-compliant" /> : <AlertTriangle className="h-3.5 w-3.5 text-halal-debated" />}<ChevronDown className="h-4 w-4 transition-transform group-open:rotate-180" /></span></summary><div className="mt-4 border-t border-white/10 pt-3 text-[11px] leading-5 text-muted-foreground"><p>{criterion.explanation}</p><p className="mt-2">Période : {criterion.fiscalPeriod ?? "—"} · Confiance : {criterion.confidence}{criterion.dataSource && <> · Source : {criterion.dataSource}</>}</p>{criterion.ratio !== undefined && <p>Ratio : <strong className="text-white">{(criterion.ratio * 100).toFixed(2)} %</strong> · Seuil : {criterion.operator} {(criterion.threshold! * 100).toFixed(0)} %</p>}{criterion.numerator && <p>Numérateur : {criterion.numerator.value.toLocaleString("fr-FR")} {criterion.numerator.currency} · {criterion.numerator.source.provider} · {criterion.numerator.source.field}</p>}{criterion.denominator && <p>Dénominateur : {criterion.denominator.value.toLocaleString("fr-FR")} {criterion.denominator.currency} · {criterion.denominator.source.provider} · {criterion.denominator.source.field}</p>}</div></details>; }
